Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream8"
    centos.vm.box_version = "20210210.0"
    centos.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "1024"
    end
    centos.vm.provision "shell", inline: <<-SHELL
      sudo useradd updater -s /bin/bash
      sudo echo "updater:vagrant" | chpasswd
      sudo echo "updater ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      yum install -y vim git wget curl
    SHELL
  end
end